version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    networks:
      - todo-network
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: todos
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

  todo-web-application:
    image: moon1z10/k8s-learning:Todo_MySQL_Web_Application-0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
    networks:
      - todo-network
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos

networks:
  todo-network:

# Volumes
volumes:
  mysql-database-data-volume:
