apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: todo-web-application-config
            - name: MYSQL_PASSWORD
#              value: dummytodos
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: todo-web-application-secrets
            - name: MYSQL_ROOT_PASSWORD
#              value: dummypassword
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: todo-web-application-secrets
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: todo-web-application-config
          image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-database-data-volume
      restartPolicy: Always
      volumes:
        - name: mysql-database-data-volume
          persistentVolumeClaim:
            claimName: mysql-database-data-volume
